### ISSUE TITLE
meta: how should the community contribute?

### ISSUE THREAD

**Issue by twpayne** [rsc/script#4]
As a very happy and enthusiastic user of github.com/rogpeppe/go-internal/testscript, I'm very happy to see a semi-official release of the fantastically useful functionality in this module!

The obvious problem raised in https://github.com/rsc/script/pull/1 was silently fixed in https://github.com/rsc/script/commit/334f6c18cff37d66fb02d957d28daf992c18fb9f without any acknowledgment or announcement, and fixing https://github.com/rsc/script/issues/3 would require only pushing a new tag.

The description of this module says:

> Posting it here makes it available for others to try without us committing to officially supporting it.

Would you like contributions from the community? If so, would you like issues, PRs, etc.? Or is this a code dump of "as-is" software?

**Comment by twpayne** [comment]
With no response here, I asked on golang-nuts: https://groups.google.com/g/golang-nuts/c/leGd1uOXpIA

**Comment by rsc** [comment]
I apologize for not pushing the v0.0.2 tag. I thought I had done that long ago - I created it locally, just forgot to push it, apparently.

This is mostly a code dump of "as-is" software. My focus since posting it has been on other Go work. Also, I do not want this package to get ahead of Go's cmd/go/internal/script, because then more work would have to be done to un-diverge them if we do eventually pick a standard place for it and have cmd/go import it directly.
